post_install() {
	xdg-icon-resource forceupdate --theme hicolor &> /dev/null

	GR=$'\x1b[1;32m'
	NC=$'\x1b[0m'
	echo "******************************************************************************"
	echo "$GR OBS. to enable VAAPI (with VDPAU):$NC"
	echo "1. Launch VLC with$GR --ffmpeg-hw$NC parameter or add$GR ffmpeg-hw=1$NC to$GR vlcrc$NC (~/.config/vlc/)"
	echo "2. In VLC tick:$GR 'Input & Codecs' -> 'Use GPU acceleration (experimental)'$NC"
	echo "*******************************************************************************"
}

post_upgrade() {
	post_install
}

post_remove() {
	post_install
}
