post_install() {
      echo ">>> "
      echo ">>> NOTE: To disable KMix set:"
      echo ">>> AutoStart=false"
      echo ">>> in [Global] section of ~/.kde4/share/config/kmixrc"
      echo ">>> "
}

post_upgrade() {
  post_install
}

post_remove() {
      echo ">>> "
      echo ">>> NOTE: To re-enable KMix set:"
      echo ">>> AutoStart=true"
      echo ">>> in [Global] section of ~/.kde4/share/config/kmixrc"
      echo ">>> "
}
 
